// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruqoacqnbqcqqeuuvjkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cW9hY3FuYnFjcXFldXV2amtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDIzMjMsImV4cCI6MjA2NjAxODMyM30.kgIWWY-31X0eD6h16_KAMAtE1R1NXd6f1EjbGTrxBC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);